# Generated by Django 2.2.5 on 2020-05-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=5)),
                ('letters', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Clues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.BooleanField()),
                ('text', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossword.Puzzle')),
            ],
        ),
    ]
