# Generated by Django 2.2.5 on 2020-05-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='letters',
        ),
    ]
