# Generated by Django 2.2.5 on 2020-05-18 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0002_remove_puzzle_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='crossword.Puzzle'),
        ),
    ]
