# Generated by Django 2.2.5 on 2020-05-18 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0003_auto_20200518_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('col', models.IntegerField(default=0)),
                ('row', models.IntegerField(default=0)),
                ('black', models.BooleanField(default=False)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares', to='crossword.Puzzle')),
            ],
        ),
    ]
