# Generated by Django 2.2.5 on 2020-05-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0004_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='black',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='square',
            name='col',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='square',
            name='row',
            field=models.IntegerField(),
        ),
    ]
