# Generated by Django 2.2.5 on 2020-05-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0006_auto_20200518_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='number',
            field=models.CharField(default='', max_length=3),
        ),
    ]
