# Generated by Django 2.2.5 on 2020-05-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0007_auto_20200518_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='number',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
