# Generated by Django 2.2.5 on 2020-05-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0009_auto_20200518_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='author',
            field=models.CharField(default='John', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='name',
            field=models.CharField(default='puzzle_name', max_length=100),
            preserve_default=False,
        ),
    ]
