# Generated by Django 2.2.5 on 2020-06-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0010_auto_20200522_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='value',
            field=models.CharField(default=' ', max_length=1),
            preserve_default=False,
        ),
    ]
